baseURL: "https://kind-dune-04caa721e.6.azurestaticapps.net"
languageCode: en-us
title: Sajin Sabu
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Sajin Sabu"
    subtitle: Hi 👋, I’m Sajin Sabu. I’m a low-level systems developer with a strong interest in coding close to the hardware and building fast, reliable systems. I currently work at Microsoft, focusing on Windows storage and NVMe driver development. This blog is where I share my day-to-day learnings, technical experiments, and anything interesting I pick up along the way. Thanks for dropping by!

 
    imageUrl: "home/IMG_3136.jpg"
    imageWidth: 250
    imageHeight: 250
    buttons:
       - name: Resume
         url: "https://drive.google.com/file/d/1qRLSXvhcSHisHP0ui8E1Apn8ozFryUFn/view?usp=sharing"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:ssabuus@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/ssajin"
    - name: "github"
      url: "https://github.com/sabusajin"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
